server:
  port: 8083

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: game-review
          uri: lb://GAME-REVIEW
          predicates:
            - Path=/api/v1/game/review/**

eureka: #Mapeia o eureka server para o cliente.
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka