server:
  port: 8082

spring:
  application:
    name: notification
  data:
    mongodb:
      uri: mongodb://jogomes:1234@localhost:27017/notification
  rabbitmq:
    addresses: localhost:5672

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key